### ISSUE TITLE
How to use the secrets once stored on disk

### ISSUE THREAD

**Issue by Seraf** [Docurated/concourse-vault-resource#4]
Hello @hexedpackets 
Can you provide an example how you use the secret that has been stored on the disk please ?

I guess you are doing an output on the task to export the folder ?

Then you have custom task with `jq` to get the string wanted ?
I would like to use it for the terraform module to get the aws access_key and secret_key fields.

Thanks

**Comment by hexedpackets** [comment]
Where I'm currently using it actually supports reading in JSON files directly, but jq will definitely work. One place I'm using it is to update other concourse pipelines, although for some reason I had to use absolute paths for the var files:

```yaml
jobs:
  - name: update-pipelines
    serial: true
    plan:
      - get: concourse-src
        trigger: true
      - get: vault
        params:
          paths:
            - build/aws
            - build/git
            - build/concourse
      - put: fly
        params:
          command: set-pipeline
          options: -n -p docker-images -l /tmp/build/put/vault/build/aws.json -l /tmp/build/put/vault/build/git.json -l /tmp/build/put/vault/build/concourse.json -c /tmp/build/put/concourse-src/docker-images.yml
```
You could also read in, say, the AWS secrets with jq and turn into terraforms variables with something like `jq -r '. as $orig | keys[] | "-var " + . + "=" + $orig[.]' vault/build/aws.json | xargs`. If aws.json contains `{"foo": "bar", "other": "thing"}` that would become `-var foo=bar -var other=thing` I think that would only work for a single flat dict, though, and would require something more complicated for nested variables. 

Does that help?
